## -------------------------------------------------------------------------------------
# Output saving options
## -------------------------------------------------------------------------------------
save_wsi_mask: True
save_annotations: True
save_nuclei_meta: True
save_nuclei_props: True

## -------------------------------------------------------------------------------------
# Run configurations
## -------------------------------------------------------------------------------------
independent_tile_assignment: False # see line 900, MuTILsWSIRunner.py
N_preprocesses: 30
N_postprocesses: 64
_debug: True 